### ISSUE TITLE
vue.js:596 [Vue warn]: Error in beforeDestroy hook: "TypeError: Cannot read property 'filter' of undefined"

### ISSUE THREAD

**Issue by davidverriere** [KoRiGaN/Vue2Leaflet#177] opened 2018-05-23 08:51 UTC
https://github.com/KoRiGaN/Vue2Leaflet/blob/bd7709d3b7929f4306e279ce5c5e709d8f49e48a/src/components/LMap.vue#L171

layerToAdd is null on calling removeLayer.

I do not see where layerToAdd is defined

**Comment by lordfuoco** [comment] 2018-09-28 07:41
Closing this since the issue is resolved and merged, release coming soon

**Closed by lordfuoco** 2018-09-28 07:41 UTC

**Comment by DC19950217** [comment] 2019-04-24 17:40
How can this problem be solved?
