### ISSUE TITLE
The marker icon is not displayed in a vue.js webpack template

### ISSUE THREAD

**Issue by Abdelaziz18003** [KoRiGaN/Vue2Leaflet#103] opened 2017-11-24 14:30 UTC
### Description
The marker icon can't be loaded properly when using `v-marker` as shown in the image below (in Actual results). As you can see the marker `img` element is on the DOM but the `src` url is not pointing to the correct image.

#### Steps to Reproduce
here the code I am using, it is almost the same as provided in the README

```javascript
import vue2Leaflet from 'vue2-leaflet'
export default {
  components: {
    vMap: vue2Leaflet.Map,
    vTilelayer: vue2Leaflet.TileLayer,
    vMarker: vue2Leaflet.Marker
  }
}
```

```html
<!-- show map -->
<div style="height: 300px;>
  <v-map :zoom="12" :center="[location.lat, location.lon]">
    <v-tilelayer url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"></v-tilelayer>
    <v-marker :lat-lng="[location.lat, location.lon]"></v-marker>
  </v-map>
</div>
```

#### Expected Results
The marker image get displayed properly

#### Actual Results
The marker image is on the DOM but is not displayed properly

![screenshot from 2017-11-24 15-11-21](https://user-images.githubusercontent.com/11301627/33214931-143796bc-d12e-11e7-8d44-081085c5d367.png)

### Browsers Affected
I tested it just on these browsers
- [x] Chrome
- [x] Firefox

### Versions
- Leaflet: v1.2.0
- Vue: v2.3.4
- Vue2Leaflet: v0.0.57

**Comment by psychosis448** [comment] 2017-11-25 22:22
Issue is known.
Add the following to main.js
```javascript
// eslint-disable-next-line  
delete L.Icon.Default.prototype._getIconUrl  
// eslint-disable-next-line  
L.Icon.Default.mergeOptions({  
  iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),  
  iconUrl: require('leaflet/dist/images/marker-icon.png'),  
  shadowUrl: require('leaflet/dist/images/marker-shadow.png')  
})```

That worked for me :)

**Comment by Abdelaziz18003** [comment] 2017-11-26 09:02
Thanks that worked for me too

**Comment by KoRiGaN** [comment] 2017-12-04 17:29
Hi @Abdelaziz18003,

This issue seems to be a duplicate of #28.
I'm closing this one and only keep 28 until a good / better solution is found.

Micka

**Closed by KoRiGaN** 2017-12-04 17:29 UTC

**Comment by simenJohnsen** [comment] 2021-02-16 10:09
I had to add ".default" after each of the required() files to make it work: 

`
delete Icon.Default.prototype._getIconUrl;
Icon.Default.mergeOptions({
    iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png').default,
    iconUrl: require('leaflet/dist/images/marker-icon.png').default,
    shadowUrl: require('leaflet/dist/images/marker-shadow.png').default,
});
`

**Comment by anton-kozlovsky** [comment] 2021-06-23 15:59
@simenJohnsen thanks, I was struggling to find the solution.

Is there any explanation of a cause of the problem?

**Comment by adesousa** [comment] 2023-01-26 21:42
In case of, this worked for me:
```
const { map, tileLayer, marker, icon } = await import(
      'leaflet/src/Leaflet'
)
const blueIcon = icon({
      iconUrl: '/img/front/geoloc/marker-icon.png',
      shadowUrl: '/img/front/geoloc/marker-shadow.png'
})
marker(props.marker, { icon: blueIcon }).addTo(_map)
```

**Comment by bokub** [comment] 2024-05-29 13:14
Here is how to solve the problem with imports instead of `require`:

```ts
import markerIconUrl from '/node_modules/leaflet/dist/images/marker-icon.png';
import markerIconRetinaUrl from '/node_modules/leaflet/dist/images/marker-icon-2x.png';
import markerShadowUrl from '/node_modules/leaflet/dist/images/marker-shadow.png';

L.Icon.Default.prototype.options.iconUrl = markerIconUrl;
L.Icon.Default.prototype.options.iconRetinaUrl = markerIconRetinaUrl;
L.Icon.Default.prototype.options.shadowUrl = markerShadowUrl;
L.Icon.Default.imagePath = '';
```
