### ISSUE TITLE
GeoJSON not working.

### ISSUE THREAD

**Issue by fergardi** [KoRiGaN/Vue2Leaflet#54] opened 2017-06-15 12:32 UTC
Hello.

With a simple array configuration, the geojson component is not working for me:

`v-geojson-layer(v-for="vector in map.vectors", :key="vector.id", :geojson="vector.geojson")`

Gives the following error:

![image](https://user-images.githubusercontent.com/3602272/27181297-4d6e901a-51d7-11e7-802e-79433d46e103.png)

I tried with the sample geojson https://raw.githubusercontent.com/KoRiGaN/Vue2Leaflet/master/examples/src/assets/geojson/france.json in order to check the integrity but If fails.

What to look for?

Ty.

**Comment by jteppinette** [comment] 2017-06-15 13:00
@fergardi I received this same error. I resolved it by placing a `v-if="map && map.vectors` (adjusted for variable names) on the maps parent element.

I believe the issue is from the map attempt attempting to instantiate layers before the geojson is ready.

**Comment by fergardi** [comment] 2017-06-15 13:09
In order to check this behaviour, I added directly the geojson in the created hook, so its ready when it tries to render the layer. Not working, but thanks for the response.

**Comment by KoRiGaN** [comment] 2017-06-15 13:37
Hi @fergardi,

Could you please provide a link to a jsfiddle for example that reproduce this issue.

I'm not sure how to reproduce this.
Thanks

**Comment by AchilleAsh** [comment] 2017-06-23 12:38
Hi @fergardi,

Just had the same issue while trying to load GeoJSON from a REST API (loading from hardcoded values works fine), and I’ve found a fix after reading the code.

The error is in **GeoJSON.vue** component, line 11 :
```javascript
    if (this.$parent._isMounted) {
>>   this.deferredMountedTo(this.$parent.$geoJSON);
    }
```

The parent of the GeoJSON layer is undefined, as we try to access **$geoJSON** attribute of **this.$parent**, which is the Vue Component of the map.  So later in **deferredMountedTo**, we call **this.$geoJSON.addTo(parent)** and that’s causing the error : **$geojson** is undefined in **this.$parent**.

 So replace **this.$parent.$geoJSON** with **this.$parent.mapObject** and now it’s working properly (at least in my app, let me know if it fixes your too)

@KoRiGaN I think you can reproduce this bug by using a delayed load of hardcoded values (ie. simulating an async call to an API)

Cheers

**Comment by KoRiGaN** [comment] 2017-06-27 11:58
Hi @fergardi,

I had a look and your right about the issue and was able to reproduce it by loading geojson asynchronously.
The fix you suggested also work so I push it on a new version 0.0.51.
Thanks for the great help !

@fergardi and @jteppinette, can you confirm it also fix your issues with the GeoJSON component ?

Micka

**Comment by KoRiGaN** [comment] 2017-07-06 16:04
@fergardi @jteppinette any update ?

**Comment by KoRiGaN** [comment] 2017-07-11 06:13
Closed as no answer for 2 weeks

**Closed by KoRiGaN** 2017-07-11 06:13 UTC

**Comment by bidhan-a** [comment] 2017-07-20 08:02
Hi, I'm still facing this issue on version 0.0.51.

**Comment by AchilleAsh** [comment] 2017-07-20 08:58
@KoRiGaN (cc @bidhan-a ),

I've checked your fix, there is a typo (on line 11)
```this.$parent.$mapObject ``` should be ``` this.$parent.mapObject```

There is a __$__ right before __mapObject__, that's why it's not working.



Timothé
