### ISSUE TITLE
Updating LMap's zoom prop doesn't seem reliable

### ISSUE THREAD

**Issue by francoismartineau** [KoRiGaN/Vue2Leaflet#209] opened 2018-08-14 15:37 UTC
In this example, the data passed to the zoom prop is assigned a constant every second.
Unfortunately, if the user manually sets the zoom, the assignation will not be effective anymore.
https://jsfiddle.net/k04zpLx9/2594/

Interestingly, this other example doesn't seem to display the problem.
Note that the data is now incremented instead of being assigned a constant.
https://jsfiddle.net/k04zpLx9/2596/

Help would be greatly appreciated!
Thanks,
François

**Comment by francoismartineau** [comment] 2018-08-14 20:30
I think I found a solution, but I can't explain myself why it works. Assigning "update:zoom" bus events to my local zoom variable seems to fix the bug.
https://jsfiddle.net/k04zpLx9/2603/

**Comment by farnabaz** [comment] 2018-08-25 20:54
Actually its not a bug, when user changes map zoom level you must update your local zoom value (as you do in by listening to `update:zoom` event
Without using `update:zoom` event, you repeatedly pass number 13 to map as `zoom` level, since you does not update your zoom level on user interact your local zoom data is 13 and on every second you pass 13 to map.

Here is a simple question, is 13 is not equal to 13?
The answer in No, so vue thinks that props value does not change and nothing happens

**Comment by lordfuoco** [comment] 2018-10-02 08:19
Also update:zoom means that the binding can be done with `.sync` attribute:
https://vuejs.org/v2/guide/components-custom-events.html#sync-Modifier
Closing this since it solved I think

**Closed by lordfuoco** 2018-10-02 08:19 UTC
