### ISSUE TITLE
deferredMountedTo is not a function?

### ISSUE THREAD

**Issue by bencooper222** [KoRiGaN/Vue2Leaflet#52] opened 2017-06-08 01:25 UTC
I'm trying the following code
```
<v-map :zoom="zoom" :center="center" id="map" >
    <v-tilelayer :url="url" ></v-tilelayer>
    <marker-popup :position="marker" title="Hey"> </marker-popup> 
</v-map>
```
where marker-popup's template is:
```
<template>
    <v-marker :lat-lng="position" :title="title" :draggable="false">
      <v-popup :content="text"></v-popup>
    </v-marker>
</template>
```

I get this error: 
[Vue warn]: Error in mounted hook: "TypeError: this.$children[e].deferredMountedTo is not a function.

Is there something special that I have to do to get this to work?

**Comment by bencooper222** [comment] 2017-06-08 02:57
I'm pretty convinced this is because my custom component doesn't include a function called deferredMountedTo()... which it should not reasonably be expected to include. The easy workaround for this one is to just use messy code instead of my custom component. That said, this is still a pretty serious flaw.

**Comment by KoRiGaN** [comment] 2017-06-15 13:34
Hi @bencooper222,

Yes, at the moment it was not meant to use custom component inside the map.
I think this is the only requirement for a custom component to work properly.

At the moment you have two solutions

- Use messy code,
- Use custom component that define an empty deferredMountedTo method

It would be better to make deferredMountedTo optional. I will try to implement that soon.

**Comment by dithyrambe** [comment] 2017-06-15 15:14
Oh, that's nice ! 
I had the same issue using vue2-leaflet. 

Doing so (an empty `deferredMountedTo`), does the `vue2-leaflet` component (as Polygon) inside the custom one inherit the `mapObject` property from the parent (map) of the custom one (mine) ?

Dithyrambe

**Comment by KoRiGaN** [comment] 2017-06-27 12:08
Hi @dithyrambe,

No it will not. I will just make the error message go away.

Mickael

**Comment by nowakjestem** [comment] 2017-09-22 10:33
I tried to add empty `deferredMountedTo` method in my custom marker component and as you said, error disappeared, but markers still doesn't render. Any plans on fixing this?

**Comment by bencooper222** [comment] 2017-09-22 16:37
He said "I will try to implement it soon".

**Comment by KoRiGaN** [comment] 2017-09-26 17:56
Hi @nowakjestem,

Could you please share your example as a JSFiddle so I can investigate it ?

Cheers,

Mickaël

**Comment by Axel92Dev** [comment] 2017-11-14 08:28
I've encountered this problem when using some Vuetify component inside the v-map.
![image](https://user-images.githubusercontent.com/7611180/32769926-01ab5c9e-c91e-11e7-9b04-4a1139d3d7a5.png)

The problem is this: 
![image](https://user-images.githubusercontent.com/7611180/32769954-23549bbc-c91e-11e7-845a-59d49b2711dd.png)
Inside Map.vue

**Comment by KoRiGaN** [comment] 2017-11-14 09:20
Hi @Axel92Dev,

The toolbar is not part of Vue2Leaflet so it doesn't know how/where to add it to the map.
The deferredMountedTo error will be suppressed today in a new release. However, it doesn't mean your example will be working as you want.

Why don't you add it outside the map and make it appear over it like in this [example](https://stackoverflow.com/questions/17537496/bootstrap-row-over-leaflet)?

I think it's the best way to have it work at the moment.

**Comment by KoRiGaN** [comment] 2017-11-14 12:45
Hi @bencooper222, @nowakjestem, @dithyrambe, @Axel92Dev,

Hi @Fillah,

Having custom content like a button or any Vue component inside the popup should now work with release v0.0.57.

Please let me know if it fixes your problem.
Cheers,

Mickaël

**Comment by KoRiGaN** [comment] 2017-12-04 17:27
Closing as v0.0.057 should fix this and no comment for a while.

**Closed by KoRiGaN** 2017-12-04 17:27 UTC
