### ISSUE TITLE
L.Icon.Default errors using vue-loader and webpack | Duplicated Marker

### ISSUE THREAD

**Issue by jteppinette** [KoRiGaN/Vue2Leaflet#28] opened 2017-04-28 20:49 UTC
# System Information | Affected Versions
```
leaflet: 1.0.3
vue2-leaflet: 0.0.47
vue: 2.2.6
chrome: 58.0.3029.81 (64-bit)
```

# Description
In `v.0.0.47`, I have noticed an issue with the `Marker` component being duplicated/shadowed when rendered in the map.

# Code
```
<v-map :zoom=15 :center="[organization.latitude, organization.longitude]">
    <v-tilelayer :token="mapboxAPIKey" url="https://api.mapbox.com/v4/mapbox.streets/{z}/{x}/{y}.png?access_token={token}"></v-tilelayer>
    <v-marker :lat-lng="{'lat': organization.latitude, 'lng': organization.longitude}">
        <v-popup :content="organization.name"></v-popup>
    </v-marker>
</v-map>
```

*edit: fixed code copy paste error*

# Fix
If I remove the `transform: translate3d(395px, 200px, 0px)` style from the `img.leaflet-marker-icon`, then the issue is resolved. 

*Edit:* This change seems to move the "clickable" marker out of the pane, so it cannot be used as the trigger for a popup. The incorrect "fat" marker is the one that remains. I will look into other possible "full" resolutions.

# Attachments
<img width="646" alt="screen shot 2017-04-28 at 4 47 52 pm" src="https://cloud.githubusercontent.com/assets/28163511/25546765/7cfcbaa2-2c32-11e7-8828-2f971931dc46.png">

**Comment by KoRiGaN** [comment] 2017-05-01 20:40
Hi @jteppinette,

I can't reproduce this issue. [Here](https://jsfiddle.net/b36Lfcda/1/) is a link to my attempt to reproduce it. If you can contribute to it to reproduce it that would be great !

In you example, I noticed you close v-tilelayer twice, and put v-marker inside it.
Marker should be added to map not tile layer.
```
<v-map :zoom=15 :center="[organization.latitude, organization.longitude]">
    <v-tilelayer :token="mapboxAPIKey" url="https://api.mapbox.com/v4/mapbox.streets/{z}/{x}/{y}.png?access_token={token}"></v-tilelayer>
        <v-marker :lat-lng="{'lat': organization.latitude, 'lng': organization.longitude}">
            <v-popup :content="organization.name"></v-popup>
        </v-marker>
    </v-tilelayer>
</v-map>
```

Micka

**Comment by jteppinette** [comment] 2017-05-01 23:14
@KoRiGaN Thanks for taking a look at this. I have fixed the copy/paste mistake you noticed in my issue description.

I have tried to recreate this issue in the fiddle, but I have been unable to. Do you know what would cause this to be happening locally? The main differences between the fiddle and my local instance is webpack and vuetify. I tried wrapping your fiddle with the vuetify components I am using, but I still couldn't recreate the issue.

**Comment by jteppinette** [comment] 2017-05-01 23:30
If I set `display:none ` on `leaflet-pane leaflet-shadow-pane` , then the incorrect marker will disappear.

**Comment by KoRiGaN** [comment] 2017-05-02 06:43
I'm using webpack without any issue.
I don't use vuetify at the moment.

Did you find out what caused this issue ?

**Comment by MichalKrakow** [comment] 2017-05-03 19:48
I've setup my project using laravel mix (basically webpack with some extra config on top of it)
the shadow image url is:
`http://localhost:3000/images/vendor/leaflet/dist/marker-icon.png?2273e3d8ad9264b7daa5bdbf8e6b47f8&quot;)marker-shadow.png`
so it uses the icon as shadow :).

With this level of f.ups i think webpack will not be here for very long. So if it looks familiar to someone please throw a hint.

**Comment by jteppinette** [comment] 2017-05-03 20:57
Okay, interesting find. Yeah, my marker icons are being brought in as the following:
```
http://localhost:8080/assets/images/marker-icon.png?2273e3d8ad9264b7daa5bdbf8e6b47f8%22)marker-icon-2x.png
http://localhost:8080/assets/images/marker-icon.png?2273e3d8ad9264b7daa5bdbf8e6b47f8%22)marker-shadow.png
```

However, the Chrome preview shows them as being the same image. And, `node_modules/leaflet/dist/images` clearly shows `marker-icon.png     marker-shadow.png`.

The url encoded characters `%22)` are `")`, so it looks like there could be some javascript runoff into the image urls.

**Comment by jteppinette** [comment] 2017-05-03 21:17
Okay, I found where the `Leaflet` people are discussing this issue with webpack: https://github.com/Leaflet/Leaflet/issues/4968

They proposed this solution:
```
delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({
  iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
  iconUrl: require('leaflet/dist/images/marker-icon.png'),
  shadowUrl: require('leaflet/dist/images/marker-shadow.png'),
});
```

**Comment by jteppinette** [comment] 2017-05-03 21:35
@MichalKrakow @KoRiGaN 

I can confirm that my issue has been fixed by adding the following code to one of my single file components:

```
import L from 'leaflet';

L.Icon.Default.imagePath = '/';
L.Icon.Default.mergeOptions({
    iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
    iconUrl: require('leaflet/dist/images/marker-icon.png'),
    shadowUrl: require('leaflet/dist/images/marker-shadow.png'),
});
```

I assume that this would break the normal browser use case if this change was made to the repo. Do ya'll think we should just close this ticket and leave it to the Leaflet/Webpack community to come up with a better fix on their ends?

Thanks a ton for the help guys!

**Comment by MichalKrakow** [comment] 2017-05-04 07:49
with me:
`import Vue2Leaflet from 'vue2-leaflet';

L.Icon.Default.imagePath = '.';
L.Icon.Default.mergeOptions({
    iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
    iconUrl: require('leaflet/dist/images/marker-icon.png'),
    shadowUrl: require('leaflet/dist/images/marker-shadow.png'),
});`

did the trick.
Probably it's not best practise to keep relative path in js but it have to do for now.

**Comment by KoRiGaN** [comment] 2017-05-16 12:22
Change this issue title to better describe the issue.

Mickaël

**Comment by dewdad** [comment] 2017-06-05 15:06
I'm using Vue PWA template and the following does not work for me:
```
<template>
  <div class="map">
    <v-map :zoom=13 :center="[47.413220, -1.219482]">
      <v-tilelayer url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"></v-tilelayer>
      <v-marker :lat-lng="[47.413220, -1.219482]"></v-marker>
    </v-map>
  </div>
</template>

<script>
import Vue2Leaflet from 'vue2-leaflet'

L.Icon.Default.imagePath = ''; // '/' doesn't work either
L.Icon.Default.mergeOptions({
    iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
    iconUrl: require('leaflet/dist/images/marker-icon.png'),
    shadowUrl: require('leaflet/dist/images/marker-shadow.png'),
});

export default {
  components: {
    'v-map': Vue2Leaflet.Map,
    'v-tilelayer': Vue2Leaflet.TileLayer,
    'v-marker': Vue2Leaflet.Marker
  },
  name: 'hello'
}
</script>


<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
@import "~leaflet/dist/leaflet.css";

div.map{
  width: 800px;
  height: 600px;
}
</style>
```

The inlined base64 image is is missing a quote and closing parenthesis or something. Has anyone solved this? Maybe a css override solution?

**Comment by bytebrain** [comment] 2017-08-04 11:37
I've got it working by deleting the `_getIconUrl` prototype first.

Here is my complete working component:
```
<template>
  <div>
    <v-map class="mini-map" :zoom=13 :center="[47.413220, -1.219482]">
      <v-tilelayer url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"></v-tilelayer>
      <v-marker :lat-lng="[47.413220, -1.219482]"></v-marker>
    </v-map>
  </div>
</template>

<script>
import L from 'leaflet'
import Vue2Leaflet from 'vue2-leaflet'

// Build icon assets.
delete L.Icon.Default.prototype._getIconUrl
L.Icon.Default.imagePath = ''
L.Icon.Default.mergeOptions({
  iconRetinaUrl: require('../assets/markers/marker-icon-2x.png'),
  iconUrl: require('../assets/markers/marker-icon.png'),
  shadowUrl: require('../assets/markers/marker-shadow.png')
})

export default {
  components: {
    'v-map': Vue2Leaflet.Map,
    'v-tilelayer': Vue2Leaflet.TileLayer,
    'v-marker': Vue2Leaflet.Marker
  }
}
</script>

<style lang="scss">
@import "~leaflet/dist/leaflet.css";

.mini-map {
  width:100%;
  height:250px !important;
}
</style>
```

**Comment by KoRiGaN** [comment] 2017-09-26 17:51
PR Leaflet/Leaflet#5771 seems to be a fix for that kind of issue with webpack.

Wait and see.

**Comment by eralogos** [comment] 2018-11-02 04:11
I encountered the same problem.
According to the quotes in leaflet.css file:

                // @option imagePath: String
		// `Icon.Default` will try to auto-detect the location of the
		// blue icon images. If you are placing these images in a non-standard
		// way, set this option to point to the right path.

Try add a imagePath string in the options object, like this:

               imagePath: 'images/vendor/leaflet/dist/'

**Comment by tiangolo** [comment] 2019-01-06 09:40
There's now a plug-in, at the Leaflet level, to solve this: https://github.com/ghybs/leaflet-defaulticon-compatibility.

It's working well for me. And I'm also using Vue2Leaflet.

Maybe it's worth adding it to the docs?

**Comment by DonNicoJs** [comment] 2019-04-21 14:53
closing here and adding a new issue to update the docs with the info collected in this thread

**Closed** 2019-04-21 14:53 UTC
