### ISSUE TITLE
Filter GeoJson (multiple dynamic) and recalculate displayed markers

### ISSUE THREAD

**Issue by SylwiaJeziorska** [KoRiGaN/Vue2Leaflet#217] opened 2018-09-07 06:39 UTC
Sorry for asking the question here, but I have no answer on stackoverflow.
I'm creating my GeoJson from props which works fine. Now I would like to let users filter the localization by some checkbox inputs (city, region, country...).
I have too much data with too many criteria to create different layers.
Whatever I try I have always the same problem between data which is already displayed and the one which was changed after the component loaded. Because the points were displayed when the date was downloaded, they are not reactive to the user choice.

What should I do? Reload the component or rather send props when the data is ready after user clicking?

**Comment by lordfuoco** [comment] 2018-09-10 08:29
In one of our the project using VueLeaflet I have the same issue: recalculate the gjson layer based on user input. I am successfully using this technique:
v-if the l-geo-json item.
When the 'data that filter the geo-json' change watch it, set the v-if to false, change the date and set it the v-if to true again:

```
 if (this.id) {
          this.id = null;
          this.$nextTick(() => {
            this.id = id;
          });
        } else {
          this.id = id;
        }
```
This is a copy-pasted snippet from my watcher, I hope this helps!

**Comment by lordfuoco** [comment] 2018-09-21 09:09
@SylwiaJeziorska Did you manage to fix your problem ?

**Comment by SylwiaJeziorska** [comment] 2018-09-21 09:58
Yes. Thanks for your help. 
It was enough to reload the component.
My problem is that I do not have any experience with vue.js.

**Comment by lordfuoco** [comment] 2018-09-21 11:31
@SylwiaJeziorska Glad to hear! do you know about the discord server VueLand ? where the VueJs community hangs out ? There you can find help or reach out directly to me too (DonNico)
If the issue is closed please close the issue! :)

**Closed** 2018-09-21 11:59 UTC
