### ISSUE TITLE
Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

### ISSUE THREAD

**Issue by Fillah** [KoRiGaN/Vue2Leaflet#146] opened 2018-03-27 13:25 UTC
Hey KoRiGaN.

I just installed Vue2-leaflet 0.0.60 to my project and followed your simple example on how to set it up, which works. The problem appears when i'm trying to add a popup or tooltip to my markers. The error happens on load and whenever i hover over a marker / clicks on a marker.

Error:

> Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.

I have the following code:

```
<v-map :zoom="zoom" :center="center">
    <v-tilelayer :url="url" :attribution="attribution"></v-tilelayer>
        <v-marker v-for="marker in markers" :key="marker.id" :visible="marker.visible" :draggable="marker.draggable" :lat-lng="marker.position">
            <v-popup :content="marker.tooltip" />
            <v-tooltip :content="marker.tooltip" />
      </v-marker>
</v-map>

<script>
import Vue2Leaflet from 'vue2-leaflet';

export default {
    name: 'vuejscomponent',
    components: {
        'v-map': Vue2Leaflet.Map,
        'v-tilelayer': Vue2Leaflet.TileLayer,
        'v-popup': Vue2Leaflet.Popup,
        'v-marker': Vue2Leaflet.Marker,
        'v-tooltip': Vue2Leaflet.Tooltip
    },
    data () {
        return {
            zoom: 14,
            center: [51.505, -0.09],
            url: 'http://{s}.tile.osm.org/{z}/{x}/{y}.png',
            attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors',
            markers: [
                { id: "m1", position : {lat:51.005, lng:-0.09}, tooltip: "tooltip for marker3", draggable: true, visible: true },
                { id: "m2", position : {lat:50.7605, lng:-0.09}, tooltip: "tooltip for marker4", draggable: true, visible: false }
            ],
            options: { permanent: true, custom: true, className: 'tooltipBox', custom: true, dashOffset: "" }
        }
    }
}
</script>
```

Got any suggestion how to fix this?

**Comment by KoRiGaN** [comment] 2018-03-27 13:42
Hi @Fillah,

You name your component v-XXXX so in your template make sure to use the same name.

 ``` html
<v-map :zoom="zoom" :center="center">
    <v-tilelayer :url="url" :attribution="attribution"></v-tilelayer>
        <v-marker v-for="marker in markers" :key="marker.id" :visible="marker.visible" :draggable="marker.draggable" :lat-lng="marker.position">
            <v-popup :content="marker.tooltip" />
            <v-tooltip :content="marker.tooltip" />
      </v-marker>
</v-map>
 ```

Hope this helps,

Micka

**Comment by Fillah** [comment] 2018-03-27 14:14
Sorry i was too fast writing the code. I actually do have that code you wrote and i still get the error

**Comment by KoRiGaN** [comment] 2018-03-27 15:37
@Fillah, I tried your code in this [jsfiddle](https://jsfiddle.net/Boumi/e26ywjys/) with v0.0.60 and it works.

Seems to be something related to your setup.

Can you share an example that reproduces your issue?

**Comment by Fillah** [comment] 2018-03-27 19:09
Could this be related to an "older" version of Vue, leaflet or Proj4?

Vue: 2.4.4
Leaflet: 1.0.3
Proj4: 2.4.4

**Comment by KoRiGaN** [comment] 2018-03-30 17:03
@Fillah,

I tried with different version of Vue and it worked fine.

Do you have a project available where I can test that issue and fix it?

If I'm not able to reproduce the error I'm afraid I will have to close that issue.

Mickaël

**Comment by Fillah** [comment] 2018-04-02 14:05
the project is for a customer and i therefore i can't share the project with you, sadly.
I can not seem to reproduce the error, so maybe it's just something with my build. Do you have any idea why the error would seem to appear or have any fix to it besides i have to create a new project? Maybe setup some other parameters for the tooltip or popup, which seems to be the problem.

Otherwise i'm just gonna close it and try something else. But thank you for your time and help :)

**Comment by KoRiGaN** [comment] 2018-04-03 00:03
It doesn't seem to be Vue2Leaflet related as 'Node' and 'appendChild' doesn't exist in the Vue2Leaflet codebase.

Could you try:
Only Popup (no tooltip). Does it produce the same error? 
Only Tooltip (no popup). Does it produce the same error? 
Use <v-popup></v-popup> instead of <v-popup />. Does it produce the same error ? [See here.](https://github.com/vuejs/vue/issues/1036)

Hope this helps,

Micka

**Comment by Fillah** [comment] 2018-04-03 07:28
Only popup: The error only occurs when i click on a marker and no popup shows.
Only tooltip: The error occurs on both hover and click and no popup shows.
Use instead of: Didn't work and still gives the me errors.

**Comment by Fillah** [comment] 2018-04-03 07:31
![error leaflet](https://user-images.githubusercontent.com/15626471/38235540-d235bb54-3721-11e8-8ef0-4cc2f00842c6.PNG)

**Comment by KoRiGaN** [comment] 2018-04-03 11:07
All these errors are triggered in leaflet so I don't know what is going on.
I would suggest to debug it and see what happens in leaflet popup at _updateContent and what is this._content at that time. 

I would help to narrow down possible issues and find a fix.

**Comment by kissmygritts** [comment] 2018-07-27 20:03
The following link may help narrow down this issue.

https://gis.stackexchange.com/questions/141329/error-when-trying-to-bind-popup-on-geojson-failed-to-execute-appendchild

**Comment by aluramh** [comment] 2018-08-08 22:44
This is still happening to me. It started happening out of nowhere.

**Comment by burzum** [comment] 2018-10-31 00:28
Same issue for me. :(

**Comment by lordfuoco** [comment] 2018-10-31 07:13
Did you guys tried to update to the latest version? We just released on npm a lot of bugfixes and improved the code base quite much!

**Comment by chaogis** [comment] 2018-11-07 10:19
i meet this problem yestoday when i updated vue2-leaflet from 1.0.2 to 1.1.1, while leaflet is the newest version 1.3.4. However, before update vue2-leaflet to 1.1.1, it all work fine. So, i wonder where the error come from, from vue2-leaflet or leaflet? @KoRiGaN Could you please take some attention to find it out and  solve? Thank you!

**Comment by lordfuoco** [comment] 2018-11-07 10:28
@chaogis Can you please share the code snippet that cause the error ?

**Comment by chaogis** [comment] 2018-11-07 11:57
> @chaogis Can you please share the code snippet that cause the error ?
I am glad to receive from you, following is part of my code:
`cityGeojsonOptions(){
      return {
        pointToLayer: this.pointToLayerFunction,
        onEachFeature: this.onEachFeatureFunction
      }
    },
    pointToLayerFunction(){
      return(geoJsonPoint, latlng) => {
        let factorVal = geoJsonPoint[this.factor];
        let level = 'level0';
        if(factorVal){
          level = getFactorLevel(this.factor, factorVal);
        }
        geoJsonPoint.icon = this.createIcon(level);
        return L.marker(latlng, geoJsonPoint)
              // .bindPopup(geoJsonPoint.properties.name),{
              //   //maxHeight: 20,
              //   closeButton: false,
              //   offset: [0, 2]});
      }
    },
    onEachFeatureFunction(){
      return(feature, layer) => {
        layer.on('click', e => {
          console.log('onEachFeatureFunction: Click City');
          //console.log(e);
          this.cityClick(feature.properties.cityCode);
        });
        layer.on('mouseover', e => {
          console.log('onEachFeatureFunction: MouseMove City - ' + feature.properties.cityCode);
          layer.bindPopup(feature.properties.name + ' · ' + this.factor + ': ' + feature[this.factor],
                {
                  //maxHeight: 20,
                  closeButton: false,
                  offset: [0, 2]})
              .openPopup();
        });
      }
    },`

    I think the problem appeared because leaflet 1.3.4 is conflicting with vue2-leaflet 1.3.4. Just now, i manually install leaflet of version 1.2.0, and the problem is not appearint now.
    please find why, thank you.

**Comment by chaogis** [comment] 2018-11-07 12:00
![image](https://user-images.githubusercontent.com/32628057/48130426-96224e00-e2c7-11e8-81ce-e7ad84febd00.png)
@KoRiGaN the code above is confusion， so i clip a picture of my code

**Comment by lordfuoco** [comment] 2018-11-07 12:49
@chaogis Thank you for the code, I will try to replicate the problem!

**Comment by lordfuoco** [comment] 2018-11-20 06:35
This should all be related to #281 everytime an erro appear on a webpacked app and not when importing from cdn (jsfiddle) is something related to issue #281

**Comment by lordfuoco** [comment] 2018-11-20 06:36
@chaogis please take a look at #281 too to solve your problem. Please make sure that if you have a lock file no multiple versions of vue-leaflet are listed

**Comment by core01** [comment] 2018-11-22 20:48
@HIMISOCOOL Hello, I've got the same issue. I just removed leaflet dependency, and run `npm i --save vue2-leaflet`. After that all works fine. As we can see here [package.json#L27](https://github.com/KoRiGaN/Vue2Leaflet/blob/master/package.json#L27) vue2-leaflet package has own leaflet dependency, so there is no need to install it separately.
Let me know if I'm wrong.

**Comment by chaogis** [comment] 2018-11-26 11:41
Ok, thank you very much, if i find other problems, i will write to you.



chao_gis@163.com
 
From: Nicolò Maria Mezzopera
Date: 2018-11-20 14:35
To: KoRiGaN/Vue2Leaflet
CC: chaogis; Mention
Subject: Re: [KoRiGaN/Vue2Leaflet] Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'. (#146)
Reopened #146.

**Comment by mikebronner** [comment] 2018-12-10 23:46
I also got this error when building with webpack using Node 11.x. Reverting back to Node 10 resolved the issue. Just wanted to make a note here in case it is helpful for future development or if anyone else comes across this error and they happen to be on Node 11 (current stable at the time of writing).

**Comment by lordfuoco** [comment] 2018-12-18 15:10
@mikebronner will try to test with node 11

**Comment by lordfuoco** [comment] 2018-12-18 15:13
@mikebronner I quickly tested with the examples and it works fine! can you post your package.json ? 
Also please check if #281 workaround fixes your problem.

**Comment by yokane** [comment] 2018-12-24 23:08
I found same problem. and it solved.
That cause is Leaflet's double import.

show that example, on component, 
```
import {
  L,
  LMap,
  LTileLayer,
  LMarker,
  LPopup,
  LTooltip,
  LLayerGroup
} from "vue2-leaflet";
```

and on main.js

```
import L from 'leaflet'
import 'leaflet.icon.glyph'
import 'leaflet/dist/leaflet.css'
```

After remove section of leaflet is related from main,js, runs successfully.
Though it is easy mistake, I'm glad if you can use it as a reference.

**Comment by idohurvitz** [comment] 2018-12-25 17:45
> I found same problem. and it solved.
> That cause is Leaflet's double import.
> 
> show that example, on component,
> 
> ```
> import {
>   L,
>   LMap,
>   LTileLayer,
>   LMarker,
>   LPopup,
>   LTooltip,
>   LLayerGroup
> } from "vue2-leaflet";
> ```
> and on main.js
> 
> ```
> import L from 'leaflet'
> import 'leaflet.icon.glyph'
> import 'leaflet/dist/leaflet.css'
> ```
> After remove section of leaflet is related from main,js, runs successfully.
> Though it is easy mistake, I'm glad if you can use it as a reference.



> @HIMISOCOOL @chaogis Hello, I've got the same issue. I just removed leaflet dependency, and run `npm i --save vue2-leaflet`. After that all works fine. As we can see here [package.json#L27](https://github.com/KoRiGaN/Vue2Leaflet/blob/master/package.json#L27) vue2-leaflet package has own leaflet dependency, so there is no need to install it separately.
> Let me know if I'm wrong.


hey!
i want to update my application to use vue2-leaflet and its plugins.
i read all the comments here and in issue 208 and still getting the same error,
can someone help me please?

**Comment by mikebronner** [comment] 2018-12-25 18:53
@yokane, I'm not sure if the cause for the problems we are having is the same. I am registering the components globally with Vue:

```js
import Vue2Leaflet from "vue2-leaflet";
import Vue2LeafletMarkerCluster from 'vue2-leaflet-markercluster';

Vue.component("l-attribution", Vue2Leaflet.LControlAttribution);
Vue.component("l-map", Vue2Leaflet.LMap);
Vue.component("l-marker", Vue2Leaflet.LMarker);
Vue.component("l-popup", Vue2Leaflet.LPopup);
Vue.component("l-tile-layer", Vue2Leaflet.LTileLayer);
Vue.component("l-wms-tile-layer", Vue2Leaflet.LWMSTileLayer);
Vue.component("l-zoom", Vue2Leaflet.LControlZoom);
Vue.component("v-marker-cluster", Vue2LeafletMarkerCluster);
```

Unless `vue2-leaflet-markercluster` is also importing Leaflet, in which case there might be an issue?

**Comment by kaboume** [comment] 2019-01-18 13:03
Hi,
I have the same pb.
I'm using Nuxt 

My nuxt.config file : 
` plugins: [
    { src: "~/plugins/leaflet.js", ssr: false },
  ],`

My plugins/leaflet.js file :
```

`import Vue from "vue";
import { LMap, LTileLayer, LMarker, LPopup, LTooltip } from "vue2-leaflet";

import L from "leaflet";
delete L.Icon.Default.prototype._getIconUrl;

if (process.client) {
  L.Icon.Default.mergeOptions({
    iconRetinaUrl: require("leaflet/dist/images/marker-icon-2x.png"),
    iconUrl: require("leaflet/dist/images/marker-icon.png"),
    shadowUrl: require("leaflet/dist/images/marker-shadow.png")
  });

  Vue.component("l-map", LMap);
  Vue.component("l-tilelayer", LTileLayer);
  Vue.component("l-marker", LMarker);
  Vue.component("l-popup", LPopup);
  Vue.component("l-tooltip", LTooltip);
}
`
```

And my component 

`<div id="map-wrap" style="height: 500px; width:100%">
    <no-ssr>
      <l-map :zoom="10" :center="positionInitiale">
        <l-tile-layer url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"></l-tile-layer>
        <l-marker :icon="customIcon" :lat-lng="positionMarqueurHome">
          <l-tooltip content="Eric"/>
        </l-marker>

        <l-marker
          v-for="marker in marqueurs"
          :key="marker.id"
          :lat-lng.sync="marker.position"
          @click="alert(marker)"
        >
          <l-popup :content="marker.tooltip"/>
          <l-tooltip :content="marker.tooltip"/>
        </l-marker>
      </l-map>
    </no-ssr>
  </div>`

When I hover the marker 

> hover and click and no popup shows.

**Comment by lordfuoco** [comment] 2019-01-18 13:35
To everyone please check the workaround with the alias in the meantime I finish the 2.0 
#281  check the end of the issue

**Comment by whittaker007** [comment] 2019-03-21 03:08
In case it helps anyone else I started getting this issue and in my case it turned out to be because the text source I was using in the popup/tooltip was actually numerical and I had to explicitly convert it to a string to avoid the error.

**Comment by DonNicoJs** [comment] 2019-04-21 15:09
2.0 is released since a while, closing this, feel free to re-open

**Closed by DonNicoJs** 2019-04-21 15:09 UTC
