### ISSUE TITLE
Loading with blank blocks

### ISSUE THREAD

**Issue by zhangya5847** [KoRiGaN/Vue2Leaflet#81] opened 2017-09-19 03:55 UTC
"vue": "^2.4.2",
"vue2-leaflet": "^0.0.53",
"webpack": "^2.6.1",

`<v-map class="location" ref="map" :zoom="13" :center="marker">
        <v-tilelayer url="http://{s}.tile.osm.org/{z}/{x}/{y}.png"></v-tilelayer>
        <v-marker :lat-lng="marker"></v-marker>
  </v-map>`
marker: [47.413220, -1.219482]
when loading,it just load one image,so others are blank.
Here is the screenshot：
![image](https://user-images.githubusercontent.com/15855773/30575115-2d500812-9cc4-11e7-9218-5770b29076a7.png)
Here is the devtools screenshot:

![image](https://user-images.githubusercontent.com/15855773/30575144-6c479cc4-9cc4-11e7-81c8-8c29d51252cc.png)

**Comment by KoRiGaN** [comment] 2017-09-19 09:01
Hi @zhangya5847,

Have you included the CSS stylesheet as mentioned in the readme ?
This kind of issue append without the leaflet stylesheet.

Let me know,

Cheers,
Mickaël

**Comment by KoRiGaN** [comment] 2017-10-02 11:48
Hi @zhangya5847,

I'm closing this issue as I can't reproduce this.

Please reopen this issue if you still have this issue and have more instruction on how to reproduce (like a repo or a jsfiddle). 

 Cheers,

Mickaël

**Closed by KoRiGaN** 2017-10-02 11:48 UTC

**Comment by autogestion** [comment] 2017-10-06 09:53
Got same problem. after css import, got npm error
ERROR in ./node_modules/leaflet/dist/leaflet.css
Module parse failed: .../node_modules/leaflet/dist/leaflet.css Unexpected token (3:0)
You may need an appropriate loader to handle this file type.
| /* required styles */
| 
| .leaflet-pane,
| .leaflet-tile,
| .leaflet-marker-icon,
 @ ../sh_ctracker/ctracker/front_vue/map.js 8:0-33

**Comment by 3RedM0** [comment] 2017-10-06 12:15
Hi @autogestion ,

Have you included the CSS stylesheet as mentioned in the readme ?
This kind of issue append without the leaflet stylesheet.

Do you have steps to reproduce this (version of npm, vue, leaflet, veu2leafet webpack etc)?
Let me know,

Cheers,
Mickaël
