### ISSUE TITLE
How to customize map options?

### ISSUE THREAD

**Issue by dramaking** [KoRiGaN/Vue2Leaflet#78] opened 2017-09-07 22:32 UTC
I am trying to change the position of the zoom control by disable the zoom control when map init and add a zoom control with specified position afterwards. Something like this: https://stackoverflow.com/questions/22926512/customize-zoom-in-out-button-in-leaflet-js

But I don't know how to customize map options.

Try to do it like this:
```
<v-map :zoom="zoom" :center="center" ref="map" :bounds="markerGroup.getBounds()" :padding="[50, 50]" :options="{zoomControl: false}">
```
But got this error:
![screen shot 2017-09-08 at 10 30 16 am](https://user-images.githubusercontent.com/17790790/30188113-d2b8e27a-9480-11e7-8c86-5ea460792ed8.png)

**Comment by KoRiGaN** [comment] 2017-09-11 13:43
Hi @dramaking,

I can't reproduce your issue with the last version.
You can see a working example [here](https://jsfiddle.net/7b3ps92v/)

Let me know if it works for you.

Mickaël

**Comment by dramaking** [comment] 2017-09-11 21:09
Hi @KoRiGaN,
Thank you for your help. It works. Guess we have to pass a data property instead of returning an object.

**Comment by KoRiGaN** [comment] 2017-09-12 07:57
Hi @dramaking,
[Here](https://jsfiddle.net/Boumi/7b3ps92v/1/) is an example that also work with just an object.
Don't really know what was wrong in your case as I can't reproduce it.

Can I close this case ?

**Closed** 2017-09-12 22:04 UTC

**Comment by tyzefh** [comment] 2017-09-18 12:21
Hello @KoRiGaN , I reproduce something like this when my options object is a computed properties. 

[Here](https://jsfiddle.net/7b3ps92v/4/), I have an exemple to reproduce. 

Maybe my code is not good. What's the good way ?
